# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      rcBranch:
        description: 'Source branch to build'
        required: true
        type: string
      tagName:
        description: 'Tag name to create'
        required: true
        type: string
      nextRcBranch:
        description: 'Next branch to build'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a ${{ inputs.tagName }} -m "Release ${{ inputs.tagName }}"
          git push origin ${{ inputs.tagName }}

      - name: Merge RC to main
        run: |
          git checkout main
          git merge --no-ff ${{ inputs.rcBranch }} -m "Sync after ${{ inputs.tagName }}"
          git push origin main

      - name: Create next RC branch
        run: |
          git checkout -b ${{ inputs.nextRcBranch }}
          git push origin ${{ inputs.nextRcBranch }}

      - name: Merge main to next RC branch
        run: |
          git checkout ${{ inputs.nextRcBranch }}
          git merge --no-ff main -m "Sync after ${{ inputs.tagName }}"
          git push origin ${{ inputs.nextRcBranch }}

