# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      rcBranch:
        description: 'Source branch to build'
        required: true
        type: string
      tagName:
        description: 'Tag name to create'
        required: true
        type: string
      pervTagName:
        description: 'Previous tag name to create'
        required: false
        type: string
      nextRcBranch:
        description: 'Next branch to build'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: ${{ inputs.rcBranch }}

      - name: Set up Git
        id: setup_git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "<github-actions@users.noreply.github.com>"

      - name: Validate inputs
        id: validate_inputs
        run: |
          echo "RC Branch: ${{ inputs.rcBranch }}"
          echo "Tag Name: ${{ inputs.tagName }}"
          echo "Next RC Branch: ${{ inputs.nextRcBranch }}"
          # Ensure the branch exists
          if ! git show-ref --verify --quiet refs/heads/${{ inputs.rcBranch }}; then
            echo Branch ${{ inputs.rcBranch }} does not exist."
            exit 1
          fi
          # Ensure tag name is valid
          if [[ ! "${{ inputs.tagName }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
            echo "Invalid tag name: ${{ inputs.tagName }}"
            exit 1
          fi          
          # Ensure the tag does not already exist
          if git tag -l | grep -q "${{ inputs.tagName }}"; then
            echo Tag ${{ inputs.tagName }} already exists."
            exit 1
          fi

      - name: Create tag
        id: create_tag
        run: |
          # Create the tag
          echo "Creating tag ${{ inputs.tagName }} on branch ${{ inputs.rcBranch }}"
          git fetch origin ${{ inputs.rcBranch }}
          git checkout ${{ inputs.rcBranch }}
          git pull origin ${{ inputs.rcBranch }}
          git log | head -n 10
          git tag -a ${{ inputs.tagName }} -m "Release ${{ inputs.tagName }}"
          git push origin ${{ inputs.tagName }}
        
      - name: Create github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tagName }}
          release_name: "${{ inputs.tagName }}"
          body: "Release notes for ${{ inputs.tagName }}"
          generate_release_notes: true
          make_latest: true
          draft: true
          prerelease: false
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge RC to main
        id: merge_to_master
        run: |
          git fetch origin master
          git checkout master
          git pull origin master
          git log | head -n 10
          git merge --no-ff ${{ inputs.rcBranch }} -m "Sync after ${{ inputs.tagName }}"
          if [ -n "$MERGE_TO_MASTER_FAILED" ]; then
            echo "Merge to master failed, please resolve conflicts manually."
            exit -1
          else
            git push origin master
            echo "Merge to master successful."
          fi

      - name: Create next RC branch
        id: create_next_rc
        run: |
          # check if next RC branch exists, if not create it
          exists=$(git branch -r | grep "origin/${{ inputs.nextRcBranch }}")
          if [ -z "$exists" ]; then
            echo "Next RC branch does not exist, creating it."
            git fetch origin ${{ inputs.nextRcBranch }} || true
            git checkout master
            git pull origin master
            git log | head -n 10
            git checkout -b ${{ inputs.nextRcBranch }} || true
            git push origin ${{ inputs.nextRcBranch }} || true
          else
            echo "Next RC branch already exists, skipping creation."
            echo "create_status=failed" >> "$GITHUB_ENV"
            git log | head -n 10
          fi

      - name: Merge master to next RC branch
        id: merge_next_rc
        if: env.create_status == 'failed'
        run: |
          git fetch origin ${{ inputs.nextRcBranch }}
          git checkout ${{ inputs.nextRcBranch }}
          git pull origin ${{ inputs.nextRcBranch }}
          git log | head -n 10
          git merge --no-ff master -m "Sync after ${{ inputs.tagName }}" || export merge_status=failed
          if [ -n "$merge_status" ]; then
            echo "Merge to next RC branch failed, please resolve conflicts manually."
            git merge --abort
            git checkout -f master

            echo "Creating pull request to master from ${{ inputs.nextRcBranch }}"
            gh pr create --base ${{ inputs.nextRcBranch }} --head master --title "Sync after ${{ inputs.tagName }}" --body "This PR syncs the latest changes from master to the next RC branch."

            if [ $? -ne 0 ]; then
              echo "Failed to create pull request, please create it manually."
              exit 1
            fi

          else 
            git push origin ${{ inputs.nextRcBranch }}
            echo "Merge to next RC branch successful."
          fi

